#Hands_On Practice: Linear Algebra for AI

Ex_1: Working with Scalar and Vectors

In [ ]:
#importing numpy

import numpy as np
scaler=0
print(scaler)

vector = np.array([2,3,5,9,24,39])
print (vector)

#scaler to vector

scaled_vector = scaler*vector
print(scaled_vector)


#additin of vectors

vector1 = np.array([2,3,5,9,24,39])
vector2 = np.array([5,7,9,24,39,51])

add_vector = vector+vector2
print(add_vector)




0
[ 2  3  5  9 24 39]
[0 0 0 0 0 0]
[ 7 10 14 33 63 90]


#Matrix creation and simple operation

In [ ]:
matrix1 = np.array ([[1,2],[4,5]])
matrix2 = np.array ([[2,3],[6,7]])
print(matrix1)
print(matrix2)

#matrix can be multiplied if columnt of first matrix matches with rows of following matrix i.e. 2 x 2  2 x 3. Resulting matrix will be 2 x 3

add_mat= matrix1+matrix2
sub_mat= matrix1-matrix2
prd_mat= matrix1*matrix2
print(add_mat)
print(sub_mat)
print (prd_mat)

[[1 2]
 [4 5]]
[[2 3]
 [6 7]]
[[ 3  5]
 [10 12]]
[[-1 -1]
 [-2 -2]]
[[ 2  6]
 [24 35]]


mat a mat b

In [ ]:
matA = np.array ([[1,2,3],[4,5,6],[1,2,1]])
matB = np.array ([[1,1,2],[2,1,1],[1,2,1]])
print (matA)
print (matB)

matmult=np.dot(matA,matB)

print(matmult)

[[1 2 3]
 [4 5 6]
 [1 2 1]]
[[1 1 2]
 [2 1 1]
 [1 2 1]]
[[ 8  9  7]
 [20 21 19]
 [ 6  5  5]]


matrix product by index



In [ ]:
import numpy as np
matA = np.array ([[1,2],[2,3]])
matB = np.array ([[3,1],[4,6]])
print (matA)
print (matB)
#matpro = [matA[0,0] * matB[0,0], matA [0,1]* matB[1,0]], #[matA[1,0] * matB[0,0], matA [1,1]* matB[1,0], []],
print(matpro)

[[1 2]
 [2 3]]
[[3 1]
 [4 6]]
([np.int64(3), np.int64(8)],)
